blank_issues_enabled: false
contact_links:
  - name: Bluesky
    url: https://bsky.app/profile/ravendwyr.bsky.social
    about: Send a message on Bluesky.
  - name: Twitch
    url: https://www.twitch.tv/ravendwyr
    about: Send a message on Twitch.
  - name: Azeroth
    url: https://worldofwarcraft.blizzard.com/en-gb/character/eu/ghostlands/ferret
    about: Send a message in-game.
